spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/mytest
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true #sout
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true

  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
    order: 0

logging:
  level:
    org.hibernate.SQL: debug #log
    #org.hibernate.type: trace #??????? ???? ?? ??? ?????? p6spy ??
